
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzqlpknzgmvcnxwzhsmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6cWxwa256Z212Y254d3poc21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MTY0MDksImV4cCI6MjA1NzI5MjQwOX0.nHv1bvaiJUrj8ySgYyseyAPVGHj1ehMq6yj-y23xXW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
